apiVersion: v1
kind: PersistentVolume
metadata:
  name: pm-shared-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: pm-local
  hostPath:
    path: /tmp/predictive-maintaince-platform
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pm-shared-pvc
  namespace: predictive-maintenance
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: pm-local
