apiVersion: apps/v1
kind: Deployment
metadata:
  name: failure-risk-service
  namespace: predictive-maintenance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: failure-risk-service
  template:
    metadata:
      labels:
        app: failure-risk-service
    spec:
      containers:
        - name: failure-risk-service
          image: predictive_maintaince_platform-failure-risk-service:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: pm-config
          volumeMounts:
            - name: shared-data
              mountPath: /data
          ports:
            - containerPort: 8000
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: pm-shared-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: failure-risk-service
  namespace: predictive-maintenance
spec:
  selector:
    app: failure-risk-service
  ports:
    - name: http
      port: 8000
      targetPort: 8000
